<?php
/**
 * Created by PhpStorm.
 * User: Waheed Al Khateeb
 * Date: 16/04/16
 * Time: 11:14 ص
 */

namespace api\common\models;

use Yii;
use yii\db\Expression;


class UserLogin extends \api\components\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{users_logins}}';
    }

    public function rules()
    {
        return [];
    }

    /** @inheritdoc */
    public function beforeSave($insert)
    {
        if ($insert) {
            //use  INET_NTOA() to get the ip again:
            $this->setAttribute('ip',  new Expression('INET_ATON("'.\Yii::$app->request->userIP.'")'));
            $this->setAttribute('timestamp', time());
        }

        return parent::beforeSave($insert);
    }

    /** @inheritdoc */
    public function save($runValidation = true, $attributeNames = null)
    {
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }

}